version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - code:/app/
    environment:
      POSTGRES_USER: ${DB_USER:-challenger}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeMe}
    depends_on:
      - database
      - nginx
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - code:/app/
    ports:
      - '80:80'
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: mytheresa
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeMe}
      POSTGRES_USER: ${DB_USER:-challenger}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:
  db-data:
  code:
